version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            make build
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            make push
